delete from	t_dept where dept_id < 0 ;
delete from	t_dept_user ;
delete from	t_job ;
delete from	t_log ;
delete from	t_login_log ;
delete from	t_role where role_id > 0 ;
delete from	t_role_menu where role_id > 0 ;
delete from	t_user where user_id > 0 ;
delete from	t_user_config ;
delete from	t_user_role where user_id > 0 ;
delete from	m_video ;
delete from	t_alarm_info ;
delete from	t_alarm_rules where rule_id > 1 ;
delete from	t_brd_breeder ;
delete from	t_brd_field ;
delete from	t_d_cameras_config ;
delete from	t_device where device_id > 1 ;
delete from	t_device_ext ;
delete from	t_device_install ;
delete from	t_disease where disease_id > 100 ;
delete from	t_disease_record ;
delete from	t_disease_sub ;
delete from	t_disease_treat ;
delete from	t_drug where drug_id > 1000 ;
delete from	t_feed ;
delete from	t_feed_additive ;
delete from	t_heart_device ;
delete from	t_livestock ;
delete from	t_livestock_bed ;
delete from	t_livestock_dead ;
delete from	t_livestock_escape ;
delete from	t_livestock_log ;
delete from	t_livestock_out ;
delete from	t_livestock_price ;
delete from	t_livestock_purchase ;
delete from	t_livestock_shed ;
delete from	t_livestock_shedentry ;
delete from	t_livestock_shedout ;
delete from	t_livestock_type ;
delete from	t_shed_transfer ;
delete from	t_supplier ;
delete from	t_vaccine where vaccine_id > 1000 ;
delete from	t_vaccine_prevention ;
delete from	t_vaccine_record ;
delete from	t_vaccine_sub ;
